### ISSUE TITLE
Verbetering van administration init

### ISSUE THREAD

**Issue by ubaer** [S63B/Administration#1]
- Wellicht dat het niet meer goed te fixen is, maar de backend applicatie zou eigenlijk in zijn eigen folder moeten staan ( net zoals je dat bij AdministrationAngular hebt gedaan)
- Is er een reden dat de Main.java "startup.java" heet? In alle andere applicaties heet hij namelijk Main.java
- PDFgenerator.java moet gerefactored worden. Er zitten een aantal punten code is die overbodig zijn en dubbele 
- Hardcode path in PDFRest.java is not okay
- Toevoegen van JAVADOC zou niet verkeerd zijn in API
-  In de PDFRest.java doe je elke keer de PdfGenerator aanmaken als je een nieuwe rest call krijgt. pls fix

**Comment by binq1000** [comment]
Punt 1 blijft hetzelfde voor nu.
Punt 2 is gerefactored. Dit moet ook nog gebeuren in RoadPricing, waar het ook startup.Java heet.
Punt 3 aangepast, moet nog gecontroleerd worden.
Punt 4 fixed.
Punt 5, nog te doen.
Punt 6 fixed, moet nog gecontroleerd worden.

**Comment by binq1000** [comment]
Added Javadoc
