### ISSUE TITLE
Filteren van buitenlandse owners in administratie frontend

### ISSUE THREAD

**Issue by ubaer** [S63B/Administration#15]
Op dit moment is het zo dat op de achtergrond een Owner nodig is om een invoice te maken van een rit van een buitenlandse auto. Hiervoor wordt er dus een redelijk lege owner aangemaakt en in de database gezet. Bij het administratiesysteem is deze gebruiker ook zichtbaar als lege record omdat hij alleen een username heeft en geen regulieren naam. Dit moet gefilterd worden.

**Comment by brmdbr** [comment]
fix gemaakt, niet kunnen testen door errors in angular.

**Comment by brmdbr** [comment]
getest
